Test of compact points node
RobotecAI/RobotecGPULidar pull request #147
Opened 2023-04-30 12:20 UTC by nebraszka

2023-04-30 15:10 UTC, prybicki requested changes
Good code and appropriate tests. A few things to be addressed before merging. Most importantly - repeatability (add printing seed). 

Here are a few more ideas to test:
- Pass zero numbers to compact
- Try running compact without any input node
- Run node multiple times (both on same and changing data)
- Try running compact on input without IS_HIT field

2023-04-30 15:10 UTC, prybicki commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +                    EXPECT_NEAR(expectedHitPoints.at(i).xyz[2], outData.at(i)[2], EPSILON_F);
Consider using `EXPECT_EQ`. I'd expect the data to remain unchanged bit-wise.

2023-04-30 15:10 UTC, prybicki commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +                    EXPECT_NEAR(expectedHitPoints.at(i).xyz[2], outData.at(i)[2], EPSILON_F);
If it does not pass, consider comparing the data from the parent node. 
You can add a field filled with std::iota to help find indices to parent data after compaction.

2023-04-30 15:10 UTC, prybicki commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +                    EXPECT_NEAR(expectedHitPoints.at(i).intensity, outData.at(i), EPSILON_F);
ditto

2023-07-10 12:19 UTC, PiotrMrozik requested changes

2023-07-10 12:19 UTC, PiotrMrozik commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +    std::vector<::Field<XYZ_F32>::type> outData { { 2.0f, 3.0f, 5.0f }, { 7.0f, 11.0f, 13.0f }, { 17.0f, 19.0f, 23.0f } };
I was looking for 420 or 2137.

2023-07-10 12:19 UTC, PiotrMrozik commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +    int pointsCount = 1000;
ditto

2023-07-10 12:19 UTC, PiotrMrozik commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +    //  TODO: Causes Segmentation fault
Create an issue on out board pls.

2023-10-25 11:11 UTC, prybicki approved these changes
Non-critical comments that may be addressed in future PRs. Tests are good enough to merge as of now.

General hint - I think that `CompactPointsNodeTest` is being overused. It is meant to be a fixture, i.e. set up some preconditions that are required in all tests. This is not true - some tests are going their own way. The class is also used as a container for variables that could be local - e.g. `inPointCloud` or `outPointCloud`. Additionally, `removeNonHitPoints` and `setUpPointCloud` could trivially become pure functions - which is preferred. Having those declarations would improve the readability of all tests. Consider the current:

```cpp
	int pointsCount = GetParam();

	setUpPointCloud(pointsCount, genCoord, genRandHit);

	// Print random seed for reproducibility
	fmt::print(stderr, "Compact Points Node Test random seed: {}\n", randomSeed);

	runGraphWithAssertions();

	removeNonHitPoints();

	TestPointCloud expectedPointCloud(pointFields, pointCoordValues.size());
	expectedPointCloud.setFieldValues<XYZ_F32>(pointCoordValues);
	expectedPointCloud.setFieldValues<IS_HIT_I32>(pointIsHitValues);

	outPointCloud = std::make_unique<TestPointCloud>(TestPointCloud::createFromNode(compactNodes.at(0), pointFields));

	EXPECT_EQ(*outPointCloud, expectedPointCloud);
```
vs alternative with pure functions and local declarations:
```cpp
	int pointsCount = GetParam();

	auto&& [inPointCloud, inNode] = setUpPointCloud(pointsCount, genCoord, genRandHit);

	// Print random seed for reproducibility
	fmt::print(stderr, "Compact Points Node Test random seed: {}\n", randomSeed);

	runGraphWithAssertions(inNode);

	auto&& expectedPointCloud = removeNonHitPoints(inPointCloud);
	auto&& outPointCloud = TestPointCloud::createFromNode(compactNodes.at(0), pointFields);

	EXPECT_EQ(*outPointCloud, expectedPointCloud);
```
IMHO the latter looks much clearer. This is, of course, only a rough example, leaving the details for you.

2023-10-25 11:11 UTC, prybicki commented on test/src/graph/nodes/CompactPointsNodeTest.cpp
> +	}
1. Add a check that `rgl_graph_get_result_size` is 0. 
2. Add a comment that you are verifying that no overwrite is happening, it's not obvious at first sight.

2023-11-08 09:35 UTC, prybicki approved these changes

2023-11-08 12:55 UTC, merged