Feature/velocity distortion v1
RobotecAI/RobotecGPULidar pull request #170
Opened 2023-07-19 13:07 UTC by PiotrMrozik

2023-07-27 12:07 UTC, msz-rai requested changes
Good job :+1: 
Please address the comments.
I don't like the PR name also. I propose `Simple velocity distortion`.

2023-07-27 12:07 UTC, msz-rai commented on test/src/graph/nodes/VelocityDistortRaysNodeTest.cpp
> +TEST_F(VelocityDistortRaysNodeTest, use_case)
Lack of tests:
- angular velocity
- linear and angular velocities combined
- pipeline with transform node (before / after distortion)
- distance field calculation
It is OK if these tests would be added in another PR.

2023-07-27 14:45 UTC, PiotrMrozik commented on src/api/apiCore.cpp
> +	});
```suggestion
		createOrUpdateNode<VelocityDistortRaysNode>(node,
												reinterpret_cast<const Vec3f*>(linearVelocity),
												reinterpret_cast<const Vec3f*>(angularVelocity));
	});
```

2023-07-31 08:02 UTC, PiotrMrozik commented on src/graph/VelocityDistortRaysNode.cpp
> +}
```suggestion
	gpuVelocityDistortRays(stream, getRayCount(),input->getRays()->getDevicePtr(),
					offsets.value()->getDevicePtr(),
					offsets.value()->getCount(),
					sensorLinearVelocity, sensorAngularVelocity,
					distortedRays->getDevicePtr());
}
```

2023-07-31 08:10 UTC, PiotrMrozik commented on include/rgl/api/core.h
> + * The velocity of the objects being scanned by the sensor is not taken into consideration.
```suggestion
 * Creates or modifies VelocityDistortRaysNode.
 * The node distorts rays according to the linear velocity and angular velocity of the sensor.
 * NOTE! 
 * The distortion is performed in the sensor-local coordinate frame. Concidering that, This node has to be placed before TransformRaysNode. If not velocity and angular velocity have to be provided in global coordinates frame.
 * This node requires that rays time offsets are set.
 * The distortion takes int account only sensor velocity.
 * The velocity of the objects being scanned by the sensor is not taken into consideration.
```

2023-07-31 09:33 UTC, msz-rai requested changes
I have left some suggestions.
Please validate units when distorting rays.

2023-07-31 09:33 UTC, msz-rai commented on include/rgl/api/core.h
> + * If not velocity and angular velocity must be provided in the global coordinates frame.
I don't like this description.

> in the global coordinates frame.

We cannot assume that TransformRaysNode is always transforming to the global coordinate frame.

I'd describe it as:
`The velocities passed to that node must match the coordinate frame in which rays are described/transformed. E.g. ... (here put some examples)`

2023-07-31 09:33 UTC, msz-rai commented on include/rgl/api/core.h
> + * @param angularVelocity Pointer to a single 3D vector describing the delta angular velocity in radians to perform distortion in euler angles (roll, pitch, yaw).
radians is not an angular velocity unit.

2023-07-31 09:33 UTC, msz-rai commented on src/gpu/nodeKernels.hpp
> +void gpuVelocityDistortRays(cudaStream_t stream, size_t rayCount, const Mat3x4f* inRays, const float* offsets, size_t offsetsCount, const Vec3f velocity, const Vec3f angularVelocity, Mat3x4f* outRays
```suggestion
void gpuVelocityDistortRays(cudaStream_t stream, size_t rayCount, const Mat3x4f* inRays, const float* offsets, size_t offsetsCount, const Vec3f sensorLinearVelocity, const Vec3f sensorAngularVelocity, Mat3x4f* outRays);
```

2023-07-31 09:33 UTC, msz-rai commented on src/graph/NodesCore.hpp
> +	void setParameters(const Vec3f* velocity, const Vec3f* angularVelocity);
```suggestion
	void setParameters(const Vec3f* linearVelocity, const Vec3f* angularVelocity);
```

2023-07-31 09:33 UTC, msz-rai commented on src/graph/NodesCore.hpp
> +	void setParameters(const float* raysTimeOffests, size_t timeOffsetsCount);
```suggestion
	void setParameters(const float* raysTimeOffsets, size_t timeOffsetsCount);
```

2023-07-31 09:33 UTC, msz-rai commented on src/graph/SetTimeOffsetsRaysNode.cpp
> +		auto msg = fmt::format("offsets don't match number of rays. "
```suggestion
		auto msg = fmt::format("time offsets don't match number of rays. "
```

2023-07-31 09:33 UTC, msz-rai commented on test/src/graph/nodes/VelocityDistortRaysNodeTest.cpp
> +		EXPECT_NEAR(outPoints[i].y(), outPoints.begin()->y() + ( i * rayTimeOffset), EPSILON_F);
Why sensor velocity is not considered in this equation?

2023-07-31 09:33 UTC, msz-rai commented on test/src/graphTest.cpp
> +	EXPECT_RGL_SUCCESS(rgl_node_rays_velocity_distort(&velocityDistort, &testVelocity, &testVelocity));
I don't understand this change

2023-07-31 10:47 UTC, msz-rai approved these changes
LGTM

2023-07-31 10:47 UTC, msz-rai commented on include/rgl/api/core.h
> + * @param angularVelocity Pointer to a single 3D vector describing the delta angular velocity in radians per secondto perform distortion in euler angles (roll, pitch, yaw).
```suggestion
 * @param angularVelocity Pointer to a single 3D vector describing the angular velocity of the sensor in euler angles (roll, pitch, yaw). The velocity is in radians per second.
```

2023-07-31 10:47 UTC, msz-rai commented on src/api/apiCore.cpp
> +		RGL_API_LOG("rgl_node_rays_velocity_distort(node={}, linearVelocity={}, angularVelocity={})",
```suggestion
		RGL_API_LOG("rgl_node_rays_velocity_distort(node={}, linear_velocity={}, angular_velocity={})",
```

2023-07-31 10:47 UTC, msz-rai commented on src/gpu/nodeKernels.cu
> +	outRays[tid] = Mat3x4f::TRS((offsets[tid] * (sensorLinearVelocity * 0.001f)) * 1000.0f, (offsets[tid] * (sensorAngularVelocity) * 0.001f) * 1000.0f, Vec3f(1.0f, 1.0f, 1.0f)) * inRays[tid];
Please put a comment that describes why we are performing unit conversions in this way.

2023-07-31 10:47 UTC, msz-rai commented on src/gpu/nodeKernels.hpp
> +void gpuVelocityDistortRays(cudaStream_t stream, size_t rayCount, const Mat3x4f* inRays, const float* offsets, size_t offsetsCount, const Vec3f sensorVelocity, const Vec3f sensorAngularVelocity, Mat3
```suggestion
void gpuVelocityDistortRays(cudaStream_t stream, size_t rayCount, const Mat3x4f* inRays, const float* offsets, size_t offsetsCount, const Vec3f sensorLinearVelocity, const Vec3f sensorAngularVelocity, Mat3x4f* outRays);
```

2023-07-31 10:47 UTC, msz-rai commented on test/src/apiSurfaceTests.cpp
> +}
Not related to velocity distortion

2023-09-23 09:24 UTC, merged