Implement Ros2PublishRadarScanNode with tests
RobotecAI/RobotecGPULidar pull request #247
Opened 2024-01-24 08:52 UTC by prybicki

Draft until #245 is merged.

2024-01-29 12:37 UTC, msz-rai requested changes
Good job :+1:
I have left some comments to address.

2024-01-29 12:37 UTC, msz-rai commented on test/src/graph/nodes/Ros2PublishRadarScanNodeTest.cpp
> +#include <api/apiCommon.hpp>
```suggestion
#include <rgl/api/extensions/ros2.h>

#include <rclcpp/rclcpp.hpp>
#include <radar_msgs/msg/radar_scan.hpp>
```
Seems to be already resolved.

2024-01-29 12:37 UTC, msz-rai commented on test/src/graph/nodes/Ros2PublishRadarScanNodeTest.cpp
> +TEST(Ros2PublishRadarScanNodeTest, should_receive_sent_data)
```suggestion
class Ros2PublishRadarScanNodeTest : public RGLTest {};

TEST_F(Ros2PublishRadarScanNodeTest, should_receive_sent_data)
```
You should define `Ros2PublishRadarScanNodeTest` class and derive it from `RGLTest` to set the logging configuration at the test startup and call `rgl_cleanup` at the test exit.
Also, it should be a Test Fixture.

2024-01-29 12:37 UTC, msz-rai commented on test/src/graph/nodes/Ros2PublishRadarScanNodeTest.cpp
> +	rclcpp::shutdown();
No needed if RGL initialized `rclcpp`. `Ros2InitGuard` did it when creating the ROS2 publishing node. `rclcpp` will be shut down automatically when cleaning up.

2024-01-30 09:00 UTC, prybicki commented on extensions/ros2/src/api/apiRos2.cpp
> +		createOrUpdateNode<Ros2PublishRadarScanNode>(node, topic_name, frame_id);
Fixed + removed default params.

2024-01-30 09:02 UTC, prybicki commented on extensions/ros2/src/api/apiRos2.cpp
> +	rgl_node_points_ros2_publish(&node, yamlNode[1].as<std::string>().c_str(), yamlNode[2].as<std::string>().c_str());
And the function being called is wrong ;)

2024-01-30 09:45 UTC, msz-rai approved these changes
LGTM

2024-01-30 10:06 UTC, merged