Feature/reflectivity
RobotecAI/RobotecGPULidar pull request #341
Opened 2024-12-04 17:28 UTC by PiotrMrozik

This pull request introduces the concept of reflectivity to the RaytraceNode, allowing for the calculation and configuration of reflectivity values in ray-tracing operations.

### Reflectivity Feature Addition:

* Added `RGL_FIELD_REFLECTIVITY_F32` to the `rgl_field_t`.
* Introduced the function `rgl_node_raytrace_configure_reflectivity_alpha` to configure reflectivity alpha values for RaytraceNode 
* Modified GPU kernels to handle reflectivity calculations and storage.

### Testing:

* Added a new test file `reflectivityTest.cpp` to cover the new reflectivity functionality.

2024-12-10 12:15 UTC, prybicki requested changes

2024-12-10 12:15 UTC, prybicki commented on include/rgl/api/core.h
> + * Default reflectivity alpha is set to 0.1f.
What's the reason behind this `0.1f` choice?

2024-12-10 12:15 UTC, prybicki commented on src/gpu/nodeKernels.cu
> +	}
Here you can use selected sample to compute reflectivity. This way reflectivity can be removed from multi-return samples to save memory.
This suggestion was NOT COMPILED.
```suggestion
	if (ctx->reflectivityF32 != nullptr) {
		auto distance2 = ctx->mrSamples.intensity[sampleIdx] * ctx->mrSamples.intensity[sampleIdx];
		ctx->reflectivityF32[returnPointIdx] = reflectivityAlpha * ctx->mrSamples.intensity[sampleIdx] * distance2;
	}
```

2024-12-10 12:15 UTC, prybicki commented on src/gpu/MultiReturn.hpp
> +	Field<REFLECTIVITY_F32>::type* reflectivity;
Remove

2024-12-10 12:15 UTC, prybicki commented on test/src/scene/reflectivityTest.cpp
> +	auto [alpha, value] = GetParam();
Please parametrize also distance.

2024-12-16 09:34 UTC, PiotrMrozik commented on include/rgl/api/core.h
> + * Default reflectivity alpha is set to 0.1f.
No particular reason. There should be some default, and a value smaller than 1.0 (for now) is safer regarding "exploding values".
Happy to hear any suggestions.

2024-12-16 11:58 UTC, prybicki commented on test/src/scene/reflectivityTest.cpp
> +		printf("Distance: %f, Intensity: %f, Reflectivity: %f, Alpha: %f\n", outDdistance, intensity, reflectivityValue, alpha);
```suggestion
		float outDistance = outDistance.at(i);
		float intensity = outIntensity.at(i);
		float reflectivityValue = alpha * outDistance * outDistance * intensity;
```

2024-12-16 13:41 UTC, prybicki approved these changes

2024-12-16 13:42 UTC, merged